services:
  memento-mori:
    image: ghcr.io/coachfire/memento-mori:latest
    volumes:
      - ./:/app/workspace
      - ./output:/output
    environment:
      - PYTHONUNBUFFERED=1
    command: --search-dir /app/workspace --output /output
